"""Congregation seeder data.

This seeder creates initial congregation data for development/testing.
Includes data scraped from chwz.info.pl/lista-zborow/ with status "need_verification".
"""

CONGREGATIONS = [
    {
        "name": "Zbór Warszawa I",
        "description": "Zbór Warszawa I - chwz.waw.pl",
        "owner_email": "jan.madeyski@gmail.com",
        "owner_name": "Jan Madeyski",
        "owner_role": "diakon",
        "address": {
            "street": "ul. Przyce 21",
            "city": "Warszawa",
            "postal_code": None,
            "province": "mazowieckie",
            "country": "PL",
        },
        "service_times": [
            {"day": "niedziela", "time": "11:00"},
            {"day": "środa", "time": "19:00"},
            {"day": "piątek", "time": "19:00"},
        ],
        "website": "chwz.waw.pl",
        "service_contact": {"name": "Jan Madeyski", "title": "Diakon"},
        "status": "published",
    },
    {
        "name": "ZBÓR ,,GENEZARET” W BARLINKU",
        "description": "ZBÓR ,,GENEZARET” W BARLINKU",
        "owner_email": "arkadiusz.wawrzyniak@op.pl",
        "owner_name": "Arkadiusz Wawrzyniak",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Tunelowa 6",
            "city": "Barlinek",
            "postal_code": "74-320",
            "province": "zachodniopomorskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Arkadiusz Wawrzyniak",
            "title": "Pastor",
            "email": "arkadiusz.wawrzyniak@op.pl",
            "phone": "669 570 797",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W BRZEGU",
        "description": "ZBÓR W BRZEGU",
        "owner_email": "jbkoszt@wp.pl",
        "owner_name": "Jacek Kosztowniak",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Garbarska 15",
            "city": "Brzeg",
            "postal_code": "49-306",
            "province": "opolskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Jacek Kosztowniak",
            "title": "Pastor",
            "email": "jbkoszt@wp.pl",
            "phone": "661 115 904",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W BYSTRZYCY KŁODZKIEJ",
        "description": "ZBÓR W BYSTRZYCY KŁODZKIEJ",
        "owner_email": "zbior.zbr-w-bystrzycy-kodzkiej@example.com",
        "owner_name": "Andrzej Walawski",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Okrzei 20",
            "city": "Bystrzyca Kłodzka",
            "postal_code": None,
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "niedziela", "time": "11:00"}],
        "website": None,
        "service_contact": {
            "name": "Andrzej Walawski",
            "title": "Pastor",
            "phone": "883 718 990",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W DANKOWICACH",
        "description": "ZBÓR W DANKOWICACH",
        "owner_email": "lupus-40@o2.pl",
        "owner_name": "Jarosław Wilczek",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Podlesie 1",
            "city": "Dankowice",
            "postal_code": None,
            "province": None,
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Jarosław Wilczek",
            "title": "Pastor",
            "email": "lupus-40@o2.pl",
            "phone": "604 394 624",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W GDAŃSKU",
        "description": "ZBÓR W GDAŃSKU",
        "owner_email": "arkadiusz.borejszo@chwz.org.pl",
        "owner_name": "Arkadiusz Borejszo",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Synów Pułku 55",
            "city": "Gdańsk",
            "postal_code": None,
            "province": "pomorskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "19:00"}],
        "website": None,
        "service_contact": {
            "name": "Arkadiusz Borejszo",
            "title": "Pastor",
            "email": "arkadiusz.borejszo@chwz.org.pl",
            "phone": "516 041 271",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W GLIWICACH- ŁABĘDACH",
        "description": "ZBÓR W GLIWICACH- ŁABĘDACH",
        "owner_email": "w.swiderski@chwz.gliwice",
        "owner_name": "Wiesław Świderski",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Staromiejska 4b",
            "city": "Gliwice",
            "postal_code": None,
            "province": "slaskie",
            "country": "PL",
        },
        "service_times": [{"day": "środa", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Wiesław Świderski",
            "title": "Pastor",
            "email": "w.swiderski@chwz.gliwice",
            "phone": "664 022 401",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W GOŁDAPI",
        "description": "ZBÓR W GOŁDAPI",
        "owner_email": "jacek.romanowski@chwz.org.pl",
        "owner_name": "Jacek Romanowski",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Partyzantów 18A",
            "city": "Gołdap",
            "postal_code": None,
            "province": "warminsko-mazurskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Jacek Romanowski",
            "title": "Pastor",
            "email": "jacek.romanowski@chwz.org.pl",
            "phone": "698 500 107",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W GRABÓWCE",
        "description": "ZBÓR W GRABÓWCE",
        "owner_email": "zborgrabowka@wp.pl",
        "owner_name": "Siergiej Zazulka",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Białostocka 44",
            "city": "Grabówka",
            "postal_code": None,
            "province": "podlaskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Siergiej Zazulka",
            "title": "Pastor",
            "email": "zborgrabowka@wp.pl",
            "phone": "794 431 354",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W KĘDZIERZYNIE-KOŹLU",
        "description": "ZBÓR W KĘDZIERZYNIE-KOŹLU",
        "owner_email": "kedzierzynchwz@wp.pl",
        "owner_name": "Grzegorz Ostrowski",
        "owner_role": "pastor",
        "address": {
            "street": None,
            "city": "Kędzierzyn-Koźle",
            "postal_code": None,
            "province": "opolskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "16:30"}],
        "website": None,
        "service_contact": {
            "name": "Grzegorz Ostrowski",
            "title": "Pastor",
            "email": "kedzierzynchwz@wp.pl",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W KĘTRZYNIE",
        "description": "ZBÓR W KĘTRZYNIE",
        "owner_email": "miroslawa.kruba@gmail.com",
        "owner_name": "Mirosław Kruba",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Zjazdowa 9",
            "city": "Kętrzyn",
            "postal_code": "11-400",
            "province": "warminsko-mazurskie",
            "country": "PL",
        },
        "service_times": [{"day": "środa", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Mirosław Kruba",
            "title": "Pastor",
            "email": "miroslawa.kruba@gmail.com",
            "phone": "790 592 925",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W KŁODZKU",
        "description": "ZBÓR W KŁODZKU",
        "owner_email": "kwiecien@post.pl",
        "owner_name": "Krzysztof Kwiecień",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Rodzinna 73-75",
            "city": "Kłodzko",
            "postal_code": None,
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Krzysztof Kwiecień",
            "title": "Pastor",
            "email": "kwiecien@post.pl",
            "phone": "500 813 774",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W KOSTRZYNIE",
        "description": "ZBÓR W KOSTRZYNIE",
        "owner_email": "marek.kalata@wp.pl",
        "owner_name": "Marek Kalata",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Żeglarska 54",
            "city": "Kostrzyn",
            "postal_code": "66-470",
            "province": "lubuskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Marek Kalata",
            "title": "Pastor",
            "email": "marek.kalata@wp.pl",
            "phone": "506 002 498",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W LEGNICY",
        "description": "ZBÓR W LEGNICY",
        "owner_email": "roman.jawdyk@chwz.org.pl",
        "owner_name": "Roman Jawdyk",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Sudecka 3",
            "city": "Legnica",
            "postal_code": "59-220",
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Roman Jawdyk",
            "title": "Pastor",
            "email": "roman.jawdyk@chwz.org.pl",
            "phone": "518 018 095",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W LESZNIE",
        "description": "ZBÓR W LESZNIE",
        "owner_email": "h.mroz@tlen.pl",
        "owner_name": "Henryk Mróz",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Edwarda Raczyńskiego 8",
            "city": "Leszno",
            "postal_code": None,
            "province": "wielkopolskie",
            "country": "PL",
        },
        "service_times": [{"day": "środa", "time": "19:00"}],
        "website": None,
        "service_contact": {
            "name": "Henryk Mróz",
            "title": "Pastor",
            "email": "h.mroz@tlen.pl",
            "phone": "502 515 060",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W LUBINIE",
        "description": "ZBÓR W LUBINIE",
        "owner_email": "remig11@wp.pl",
        "owner_name": "Remigiusz Mamrosz",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Budowniczych LGOM 10",
            "city": "Lubin",
            "postal_code": None,
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:30"}],
        "website": None,
        "service_contact": {
            "name": "Remigiusz Mamrosz",
            "title": "Pastor",
            "email": "remig11@wp.pl",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W LUBSKU",
        "description": "ZBÓR W LUBSKU",
        "owner_email": "mariuszs71@wp.pl",
        "owner_name": "Mariusz Sawron",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Budowlanych 2",
            "city": "Lubsko",
            "postal_code": "66-300",
            "province": "lubuskie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Mariusz Sawron",
            "title": "Pastor",
            "email": "mariuszs71@wp.pl",
            "phone": "602 414 198",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W ŁODZI",
        "description": "ZBÓR W ŁODZI",
        "owner_email": "bellux@op.pl",
        "owner_name": "Leszek Bijak",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Rogozińskiego 23",
            "city": "Łódź",
            "postal_code": "90-001",
            "province": "lodzkie",
            "country": "PL",
        },
        "service_times": [{"day": "środa", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Leszek Bijak",
            "title": "Pastor",
            "email": "bellux@op.pl",
            "phone": "603 064 015",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W MARKTREDWITZ (Freie Christengemeinde)",
        "description": "ZBÓR W MARKTREDWITZ (Freie Christengemeinde)",
        "owner_email": "zbior.zbr-w-marktredwitz-freie-christengemeinde@example.com",
        "owner_name": "Wiesław Chmielewski",
        "owner_role": "pastor",
        "address": {
            "street": None,
            "city": "Marktredwitz",
            "postal_code": None,
            "province": None,
            "country": "DE",
        },
        "service_times": [{"day": "piątek", "time": "19:00"}],
        "website": None,
        "service_contact": {
            "name": "Wiesław Chmielewski",
            "title": "Pastor",
            "phone": "0049 172 568",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W OLSZTYNIE",
        "description": "ZBÓR W OLSZTYNIE",
        "owner_email": "jacek.fi6@wp.pl",
        "owner_name": "Jacek Frąckowiak",
        "owner_role": "pastor",
        "address": {
            "street": None,
            "city": "Olsztyn",
            "postal_code": "10-516",
            "province": "warminsko-mazurskie",
            "country": "PL",
        },
        "service_times": [{"day": "sobota", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Jacek Frąckowiak",
            "title": "Pastor",
            "email": "jacek.fi6@wp.pl",
            "phone": "601 614 930",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W PRZEMKOWIE",
        "description": "ZBÓR W PRZEMKOWIE",
        "owner_email": "zbior.zbr-w-przemkowie@example.com",
        "owner_name": "Stefan Andrasz",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Akacjowa 7",
            "city": "Przemków",
            "postal_code": "59-170",
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {"name": "Stefan Andrasz", "title": "Pastor"},
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W RUDZIE ŚLĄSKIEJ",
        "description": "ZBÓR W RUDZIE ŚLĄSKIEJ",
        "owner_email": "baohel@wp.pl",
        "owner_name": "Daniel Wawrzyczek",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Chorzowska 8",
            "city": "Ruda Śląska",
            "postal_code": "41-709",
            "province": "slaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "17:30"}],
        "website": None,
        "service_contact": {
            "name": "Daniel Wawrzyczek",
            "title": "Pastor",
            "email": "baohel@wp.pl",
            "phone": "792 727 266",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W ŚWIEBODZINIE",
        "description": "ZBÓR W ŚWIEBODZINIE",
        "owner_email": "lukasz.tyc@wp.pl",
        "owner_name": "Łukasz Tyc",
        "owner_role": "pastor",
        "address": {
            "street": None,
            "city": "Rzuchowa",
            "postal_code": "33-114",
            "province": None,
            "country": "PL",
        },
        "service_times": [{"day": "sobota", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Łukasz Tyc",
            "title": "Pastor",
            "email": "lukasz.tyc@wp.pl",
            "phone": "600 284 205",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W TRZEBINI",
        "description": "ZBÓR W TRZEBINI",
        "owner_email": "zimeryt@interia.pl",
        "owner_name": "Andrzej Nazimek",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Piłsudskiego 122",
            "city": "Trzebinia",
            "postal_code": None,
            "province": "malopolskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Andrzej Nazimek",
            "title": "Pastor",
            "email": "zimeryt@interia.pl",
            "phone": "606 997 912",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W WARSZAWIE",
        "description": "ZBÓR W WARSZAWIE",
        "owner_email": "zbior.zbr-w-warszawie@example.com",
        "owner_name": "Tomasz Smykowski",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Przyce 21",
            "city": "Warszawa",
            "postal_code": "01-252",
            "province": "mazowieckie",
            "country": "PL",
        },
        "service_times": [{"day": "piątek", "time": "19:00"}],
        "website": None,
        "service_contact": {
            "name": "Tomasz Smykowski",
            "title": "Pastor",
            "phone": "577 106 606",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR WE WROCŁAWIU",
        "description": "ZBÓR WE WROCŁAWIU",
        "owner_email": "tomaszpekala02@gmail.com",
        "owner_name": "Tomasz Pękala",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Niedźwiedzia 17",
            "city": "Wrocław",
            "postal_code": None,
            "province": "dolnoslaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "19:00"}],
        "website": None,
        "service_contact": {
            "name": "Tomasz Pękala",
            "title": "Pastor",
            "email": "tomaszpekala02@gmail.com",
            "phone": "530 501 816",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W WYSOWEJ",
        "description": "ZBÓR W WYSOWEJ",
        "owner_email": "zbior.zbr-w-wysowej@example.com",
        "owner_name": "Józef Poręba",
        "owner_role": "pastor",
        "address": {
            "street": None,
            "city": "Wysowa",
            "postal_code": "38-316",
            "province": "malopolskie",
            "country": "PL",
        },
        "service_times": [{"day": "środa", "time": "16:30"}],
        "website": None,
        "service_contact": {"name": "Józef Poręba", "title": "Pastor"},
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W ZABRZU",
        "description": "ZBÓR W ZABRZU",
        "owner_email": "pandre@poczta.onet.pl",
        "owner_name": "Andrzej Poręba",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Sienkiewicza 30",
            "city": "Zabrze",
            "postal_code": None,
            "province": "slaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Andrzej Poręba",
            "title": "Pastor",
            "email": "pandre@poczta.onet.pl",
            "phone": "661 680 334",
        },
        "status": "published_unverified",
    },
    {
        "name": "ZBÓR W ŻORACH",
        "description": "ZBÓR W ŻORACH",
        "owner_email": "artlik@onet.eu",
        "owner_name": "Ryszard Arlt",
        "owner_role": "pastor",
        "address": {
            "street": "ul. Osińska 30b",
            "city": "Żory",
            "postal_code": "44-240",
            "province": "slaskie",
            "country": "PL",
        },
        "service_times": [{"day": "czwartek", "time": "18:00"}],
        "website": None,
        "service_contact": {
            "name": "Ryszard Arlt",
            "title": "Pastor",
            "email": "artlik@onet.eu",
            "phone": "606 143 474",
        },
        "status": "published_unverified",
    },
]
